[package]
name = "show_img"
version = "0.1.0"
authors = ["KwonJuhyeon"]
edition = "2019"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
actix-files = "0.1.1"
